# 站点信息
site_name: Cultivation Between Realms
# site_description:

# 仓库信息
repo_name: Cultivation-Between-Realms
repo_url: https://github.com/LinXinJi/Cultivation-Between-Realms

copyright: Copyright &copy; 2026-2030 LinXinJi

# 主题
theme:
  name: material
  language: zh
  # logo: 

  palette:
    # 浅色模式
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
    # 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs          # 启用标签页导航
    - navigation.sections      # 启用目录页导航
    - navigation.instant       # 启用即时预览
    - content.code             # 代码高亮
    - navigation.top           # 导航栏置顶
    - navigation.sidebar       # 左侧导航：保持默认开启，显示全局导航结构
    - toc.sidebar              # 右侧目录：启用右侧 TOC 侧边栏
    - toc.follow               # 让右侧目录跟随页面滚动高亮当前位置

# 导航
nav:
  - Home: index.md

# 
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/LinXinJi/Cultivation-Between-Realms
    - icon: fontawesome/solid/rss
      link: https://linxinji.github.io/Cultivation-Between-Realms/atom.xml
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9b23z6h
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LinXinJi_
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/LinXinJi/

# 插件
plugins: 
  - search      # 搜索插件
  - social      # 社交插件
  - blog        # 博客插件
  - rss         # RSS 订阅插件

# 额外的CSS文件
extra_css:
  - css/fonts.css

# 额外的JS文件
extra_javascript:
  - js/extra.js